/* Kody: [kategoria, nazwa, Fanuc, Sinumerik, co robi, kiedy/jak, przykład Fanuc, przykład Sinumerik, uwaga, pojęcie w słowniczku] */
var CODES = [
  ['R','Ruch szybki','G00','G0',
   'Najszybszy dojazd bez skrawania.',
   'Do podjazdu nad detal i odjazdu. Osie mogą jechać każda swoim tempem, więc tor nie musi być prostą linią — uważaj na imadło i mocowania.',
   'G00 X0. Y0.\nZ50.','G0 X0 Y0\nZ50','Nigdy nie wjeżdżaj G0 w materiał.',''],
  ['R','Ruch roboczy po prostej','G01 F__','G1 F__',
   'Skrawanie po linii prostej z posuwem F.',
   'F to posuw w mm/min (przy G94). Kod jest modalny: działa w kolejnych liniach, aż wpiszesz G0, G2 lub G3.',
   'G01 Z-5. F200\nX50. F800','G1 Z-5 F200\nX50 F800','','modalny'],
  ['R','Łuk w prawo / w lewo','G02 / G03','G2 / G3',
   'Skrawanie po łuku. G2 zgodnie z ruchem zegara, G3 przeciwnie (patrząc z góry na XY).',
   'Podajesz punkt końcowy łuku i promień (Fanuc R, Sinumerik CR=) albo środek łuku względem punktu początkowego (I, J, K).',
   'G03 X15. Y15. R5.','G3 X15 Y15 CR=5','Po zmianie punktu końcowego promień musi się zgadzać z nowym punktem, inaczej będzie alarm.',''],
  ['R','Postój','G04','G4',
   'Zatrzymuje ruch na chwilę, wrzeciono dalej się kręci.',
   'Np. czyste dno otworu albo pogłębienia. Fanuc: P w milisekundach lub X w sekundach. Sinumerik: F w sekundach lub S w obrotach.',
   'G04 P500','G4 F0.5','',''],
  ['R','Fazka / zaokrąglenie narożnika',', C__ / , R__','CHF=__ / RND=__',
   'Wstawia fazkę lub promień w narożniku między dwoma ruchami, bez liczenia punktów.',
   'Dopisujesz do linii, która kończy się w narożniku. W Fanuc to opcja — nie każda maszyna ją ma.',
   'G01 X50. ,R2.\nY30.','G1 X50 RND=2\nY30','',''],
  ['R','Posuw mm/min / mm/obr','G94 / G95','G94 / G95',
   'G94: F w mm na minutę (standard na frezarce). G95: F w mm na obrót wrzeciona.',
   'G95 spotkasz rzadko, np. przy wytaczaniu. Pamiętaj wrócić do G94.',
   'G95 F0.1\n...\nG94','G95 F0.1\n...\nG94','Ten sam F przy złym trybie daje zupełnie inny posuw.',''],
  ['R','Wygładzanie (obróbka szybka)','G05.1 Q1','CYCLE832',
   'Sterowanie czyta program z wyprzedzeniem i wygładza ruch przy wielu krótkich odcinkach.',
   'Do programów 3D z CAM. Bez tego maszyna zwalnia na każdym małym odcinku. Wyłączasz G05.1 Q0 / CYCLE832 z trybem wyłączenia.',
   'G05.1 Q1\n...\nG05.1 Q0','CYCLE832(0.01,_FINISH,1)\n...\nCYCLE832()','',''],

  ['U','Wybór płaszczyzny','G17 / G18 / G19','G17 / G18 / G19',
   'Mówi sterowaniu, w której płaszczyźnie liczyć łuki, korekcję promienia i cykle.',
   'G17 = XY (frez wzdłuż Z) — na frezarce pionowej prawie zawsze. G18 = ZX, G19 = YZ.',
   'G17','G17','','plaszczyzna'],
  ['U','Milimetry / cale','G21 / G20','G71 / G70',
   'Jednostki programu.',
   'W Twoim zakładzie prawie na pewno mm. Program z cali na maszynie w mm (lub odwrotnie) to 25,4× zły wymiar.',
   'G21','G71','',''],
  ['U','Absolutnie / przyrostowo','G90 / G91','G90 / G91',
   'G90: wartości od zera detalu. G91: o ile przesunąć się od miejsca, w którym jesteś.',
   'W Sinumerik możesz też zmienić tryb tylko dla jednej wartości: X=AC(10) absolutnie, X=IC(10) przyrostowo.',
   'G90 X10.\nG91 X10. (jeszcze 10 mm dalej)','G90 X10\nG91 X10','Zapomniane G91 to częsta przyczyna kolizji. Po G91 wróć do G90.','abs-inc'],
  ['U','Punkt zerowy detalu','G54–G59, G54.1 P1–P48','G54–G57, G505–G599',
   'Wybiera, od którego punktu liczone są wymiary programu.',
   'Wartości ustawiasz sondą lub ręcznie w tabeli przesunięć (Fanuc: WORK, Sinumerik: Przesunięcie punktu zerowego). G54 = np. pierwsze imadło, G55 = drugie.',
   'G54 G00 X0. Y0.','G54 G0 X0 Y0','Na Matsuurze z paletami sprawdź, który układ ma która paleta.','punkt-zerowy'],
  ['U','Ruch w układzie maszyny','G53','G53 / SUPA',
   'Ruch do pozycji liczonej od zera maszyny, nie detalu. Działa tylko w tej jednej linii.',
   'Np. odjazd Z do góry przed zmianą narzędzia, niezależnie od G54 i korekcji.',
   'G53 G00 Z0.','SUPA G0 Z0 D0','Tych wartości nie zmieniaj przy przesuwaniu programu.',''],
  ['U','Zjazd do punktu referencyjnego','G91 G28 Z0.','SUPA G0 Z0 D0 / G74',
   'Odjazd osi do punktu referencyjnego (zwykle Z do góry).',
   'W Fanuc „Z0” przy G91 znaczy: jedź do referencji przez obecną pozycję, bez ruchu po drodze.',
   'G91 G28 Z0.\nG90','SUPA G0 Z0 D0','Fanuc: G28 zawsze z G91. G90 G28 Z0. jedzie najpierw do Z0 detalu!',''],
  ['U','Przesunięcie tymczasowe','G52','TRANS / ATRANS',
   'Na chwilę przesuwa zero detalu, np. żeby zrobić ten sam kształt w innym miejscu.',
   'ATRANS w Sinumerik dodaje przesunięcie do już aktywnego. Anulujesz: G52 X0 Y0 / samo TRANS.',
   'G52 X50. Y0.\n...\nG52 X0 Y0','TRANS X50\n...\nTRANS','',''],
  ['U','Obrót układu','G68 / G69','ROT / AROT',
   'Obraca program o kąt wokół punktu w płaszczyźnie XY.',
   'Np. ten sam rowek pod kątem 30°. Wyłączasz G69 / samo ROT.',
   'G68 X0 Y0 R30.\n...\nG69','ROT RPL=30\n...\nROT','',''],
  ['U','Skalowanie','G51 / G50','SCALE / ASCALE',
   'Powiększa lub zmniejsza wymiary programu.',
   'Rzadko na produkcji. Zmienia też promienie łuków, ale nie zmienia korekcji narzędzia.',
   'G51 X0 Y0 P1.01\n...\nG50','SCALE X1.01 Y1.01\n...\nSCALE','',''],
  ['U','Lustro','G51.1 / G50.1','MIRROR / AMIRROR',
   'Odbija program względem osi, np. część lewa z programu części prawej.',
   'Sterowanie samo odwraca kierunek łuków i stronę G41/G42.',
   'G51.1 X0\n...\nG50.1 X0','MIRROR X0\n...\nMIRROR','Odbicie zamienia frezowanie współbieżne na przeciwbieżne — gorsza powierzchnia.','wspolbiezne'],

  ['K','Kompensacja promienia','G41 / G42 D__','G41 / G42',
   'Sterowanie odsuwa frez od konturu o jego promień z tabeli korekcji. G41 — frez po lewej stronie konturu, G42 — po prawej (patrząc w kierunku ruchu).',
   'Dzięki temu program idzie po konturze z rysunku, a wymiar poprawiasz w tabeli zużycia, nie w programie. Przy M3 frezowanie współbieżne to G41.',
   'G41 D5 X20. Y0.','G41 X20 Y0','Włączaj i wyłączaj w ruchu G1 lub G0, poza materiałem, na odcinku dłuższym niż promień freza.','kor-promienia'],
  ['K','Wyłączenie kompensacji promienia','G40','G40',
   'Wyłącza G41/G42 — tor wraca na środek freza.',
   'W następnym ruchu frez odsuwa się od konturu, więc wyłączaj przy odjeździe od detalu.',
   'G40 X0.','G40 X0','',''],
  ['K','Korekcja długości','G43 H__','z T i D (automatycznie)',
   'Dodaje długość narzędzia do Z, żeby Z0 w programie było na powierzchni detalu dla każdego narzędzia.',
   'Fanuc: numer H zwykle = numer narzędzia. Sinumerik: długość bierze się z aktywnego T i ostrza D.',
   'T5 M06\nG43 H5 Z50.','T5 M6\nD1\nG0 Z50','Zły numer H to od razu kolizja albo frezowanie w powietrzu.','kor-dlugosci'],
  ['K','Wyłączenie korekcji długości','G49','D0',
   'Wyłącza korekcję długości narzędzia.',
   'Zwykle na końcu programu albo przed ruchem do referencji.',
   'G49','D0','',''],

  ['C','Wiercenie','G81','CYCLE81',
   'Zwykłe wiercenie: wjazd z posuwem na głębokość, wyjazd szybki.',
   'Po cyklu każda kolejna pozycja X/Y to kolejny otwór, aż do G80. Z — głębokość, R — wysokość bezpieczna.',
   'G81 X10. Y10. Z-15. R2. F150\nX30.\nG80','CYCLE81(10,0,2,-15)','Sinumerik: parametry najwygodniej wypełnić na ekranie cyklu.','cykl'],
  ['C','Wiercenie z postojem','G82','CYCLE82',
   'Jak G81, ale z postojem na dnie.',
   'Do nawiercania, pogłębiania i fazowania — czyste, równe dno. P = czas postoju w ms.',
   'G82 X10. Y10. Z-3. R2. P300 F100','CYCLE82(...)','','cykl'],
  ['C','Wiercenie głębokie z wycofaniem','G83','CYCLE83',
   'Wierci po Q mm i za każdym razem wyjeżdża nad otwór, żeby usunąć wiór.',
   'Do głębokich otworów (ponad ok. 3× średnica) bez chłodzenia przez wrzeciono.',
   'G83 X10. Y10. Z-40. R2. Q5. F120','CYCLE83(...)','Wolniejsze niż G73, ale bezpieczniejsze przy długim wiórze.','cykl'],
  ['C','Wiercenie z łamaniem wióra','G73','CYCLE83 (łamanie wióra)',
   'Wierci po Q mm i cofa się lekko, nie wyjeżdżając z otworu.',
   'Szybsze niż G83. Dobre do stali, gdy wiór się nawija.',
   'G73 X10. Y10. Z-20. R2. Q3. F150','CYCLE83(...)','','cykl'],
  ['C','Gwintowanie sztywne','M29 S__ + G84','CYCLE84',
   'Gwintowanie gwintownikiem z ruchem posuwu zsynchronizowanym z obrotami.',
   'F = obroty × skok, np. M8 (skok 1,25) przy S500 → F625.',
   'M29 S500\nG84 X0 Y0 Z-15. R3. F625\nG80','CYCLE84(...)','Na niektórych Fanuc M29 nie jest potrzebne — zależy od parametrów maszyny.','cykl'],
  ['C','Rozwiercanie','G85','CYCLE85',
   'Wjazd i wyjazd z posuwem.',
   'Do rozwiertaka i wytaczania wykańczającego, gdy szybki wyjazd zostawiłby rysę.',
   'G85 X10. Y10. Z-20. R2. F80','CYCLE85(...)','','cykl'],
  ['C','Wytaczanie z odsunięciem noża','G76','CYCLE86',
   'Na dnie zatrzymuje wrzeciono w ustalonej pozycji i odsuwa nóż od ścianki przed wyjazdem.',
   'Ścianka otworu zostaje bez rysy. Kierunek odsunięcia ustawia się w parametrach.',
   'G76 X0 Y0 Z-20. R2. Q0.2 F60','CYCLE86(...)','Sprawdź kierunek odsunięcia, zanim nóż wjedzie w otwór.','cykl'],
  ['C','Wyłączenie cyklu','G80','MCALL (puste)',
   'Kończy cykl wiercenia.',
   'Fanuc: bez G80 każda kolejna pozycja X/Y nadal wierci. Sinumerik: cykl wywołany zwykłym CYCLE8x działa raz; MCALL włącza powtarzanie, samo MCALL je wyłącza.',
   'G80','MCALL','','modalny'],
  ['C','Powrót między otworami','G98 / G99','RTP / RFP / SDIS',
   'Na jaką wysokość wraca wiertło między otworami.',
   'G98 — do wysokości startu (omija mocowania). G99 — tylko do R (szybciej). W Sinumerik ustawiasz to w parametrach cyklu.',
   'G98 G81 ...','CYCLE81(RTP,RFP,SDIS,DP)','Przy imadle między otworami używaj G98.','plaszczyzna-r'],

  ['P','Wywołanie podprogramu','M98 P____','nazwa programu / L____',
   'Uruchamia inny program i wraca.',
   'Np. ten sam kształt na kilku detalach. Fanuc: P = numer programu (M98 P1234 lub P31234 — 3 powtórzenia).',
   'M98 P1234','KONTUR1\nL1234','',''],
  ['P','Koniec podprogramu','M99','M17 / RET',
   'Wraca do programu, który wywołał podprogram.',
   'M99 w programie głównym (Fanuc) powoduje powtarzanie programu od początku.',
   'M99','M17','',''],
  ['P','Zmienne','#1–#33, #100–#199, #500–#999','R0–R99, DEF',
   'Komórki pamięci na liczby, używane w makrach i programach z parametrami.',
   'Fanuc: #1–#33 lokalne, #100–#199 wspólne (kasowane przy wyłączeniu), #500–#999 trwałe.',
   '#100=5.\nG01 X#100','R1=5\nG1 X=R1','#500+ zostają po wyłączeniu i bywają używane przez sondę — nie nadpisuj bez sprawdzenia.',''],
  ['P','Skoki i warunki','IF … GOTO','IF … GOTOF / GOTOB',
   'Skok do innej linii programu, gdy warunek jest spełniony.',
   'Używane w makrach, np. liczniki detali i pętle.',
   'IF [#1 GT 0] GOTO 10\n...\nN10','IF R1>0 GOTOF ETYK\n...\nETYK:','',''],
  ['P','Komentarz','( TEKST )','; TEKST',
   'Tekst dla operatora — sterowanie go pomija.',
   'Dobre miejsce na nazwę narzędzia i operacji.',
   'T5 M06 (FREZ D10)','T5 M6 ; FREZ D10','',''],

  ['5','Płaszczyzna pochylona (3+2)','G68.2 + G53.1 / G69','CYCLE800',
   'Obróbka pochylonej ściany tak, jakby była płaska. Stół się pochyla i stoi, a X/Y/Z liczone są w tej pochylonej płaszczyźnie.',
   'G68.2 ustawia pochyloną płaszczyznę (kąty I, J, K), G53.1 obraca osie stołu, G69 wraca do zwykłego układu. Potem robisz zwykłe frezowanie i wiercenie.',
   'G68.2 X0 Y0 Z0 I0 J30. K0\nG53.1\n...\nG69','CYCLE800(...)','Po G68.2 korekcja i wymiary X/Y dotyczą pochylonej płaszczyzny. Zawsze zakończ G69.','pochylona'],
  ['5','TCP — kontrola czubka narzędzia','G43.4 H__ / G49','TRAORI / TRAFOOF',
   'Przy jednoczesnym ruchu 5 osi sterowanie samo dolicza ruch X/Y/Z, żeby czubek narzędzia szedł po torze z programu, mimo że stół się obraca.',
   'Używane w programach 5-osiowych z CAM. G43.4 zastępuje zwykłe G43 i też bierze długość z H. Wyłączasz G49 (Fanuc) lub TRAFOOF (Sinumerik).',
   'G43.4 H5\n...\nG49','TRAORI\n...\nTRAFOOF','Długość narzędzia musi być dokładna — błąd długości daje błąd położenia na powierzchniach pochylonych.','tcp'],

  ['M','Wrzeciono','M03 / M04 / M05','M3 / M4 / M5',
   'M3 — obroty w prawo (zwykłe skrawanie), M4 — w lewo, M5 — stop.',
   'Obroty podajesz S, np. S6000 M3.',
   'S6000 M03','S6000 M3','',''],
  ['M','Orientacja wrzeciona','M19','SPOS=__',
   'Ustawia wrzeciono w stałym położeniu kątowym.',
   'Potrzebne przy wytaczaniu i ustawianiu sondy.',
   'M19','SPOS=0','',''],
  ['M','Chłodziwo','M08 / M09','M8 / M9',
   'M8 włącza, M9 wyłącza chłodziwo.',
   'Chłodzenie przez wrzeciono i nadmuch mają kody zależne od producenta maszyny — sprawdź w dokumentacji.',
   'M08','M8','',''],
  ['M','Zmiana narzędzia','T__ M06','T__ M6 / T="NAZWA" M6',
   'T wybiera narzędzie, M6 wkłada je do wrzeciona.',
   'Na maszynach z zarządzaniem narzędziami (Sinumerik) narzędzie może mieć nazwę zamiast numeru.',
   'T5 M06','T5 M6','',''],
  ['M','Stop / stop opcjonalny','M00 / M01','M0 / M1',
   'M0 zatrzymuje program zawsze. M1 tylko, gdy włączony jest przycisk „Stop opcjonalny”.',
   'M1 przydaje się do sprawdzenia pierwszej sztuki — przy kolejnych wyłączasz przycisk.',
   'M01','M1','',''],
  ['M','Koniec programu','M30','M30 / M2',
   'Kończy program i wraca na jego początek.',
   'Zwykle po M5, M9 i odjeździe Z do góry.',
   'M30','M30','','']
];

/* Słowniczek: [id, pojęcie, wyjaśnienie] */
var GLOSSARY = [
  ['zuzycie','Zużycie (Wear, ΔR, ΔL)','Mała poprawka do wymiaru narzędzia. Tu wpisujesz korekty z pomiaru detalu. Sterowanie liczy: geometria + zużycie. Ujemne zużycie promienia = frez „chudszy”, zbiera więcej materiału. Ujemne zużycie długości = narzędzie „krótsze”, schodzi niżej.'],
  ['geometria','Geometria narzędzia','Zmierzony wymiar narzędzia: długość (z pomiaru na maszynie lub urządzeniu nastawczym) i promień. Przy korektach z pomiaru detalu zwykle jej nie zmieniasz — od tego jest zużycie.'],
  ['kor-promienia','Korekcja promienia (D)','Promień freza, o który sterowanie odsuwa tor od konturu przy G41/G42. Zmiana zużycia promienia przesuwa wszystkie ścianki konturu naraz, każdą o tę samą wartość. Dlatego otwór lub czop zmienia się o 2× korektę.'],
  ['kor-dlugosci','Korekcja długości (H)','Długość narzędzia, którą sterowanie dodaje do Z (Fanuc: G43 H, Sinumerik: automatycznie z T i D). Zmiana zużycia długości przesuwa wszystkie głębokości robione tym narzędziem.'],
  ['ostrze-d','Ostrze D (Sinumerik)','W Sinumerik każde narzędzie T ma jedno lub kilka ostrzy D z osobnymi korekcjami, np. T5 D1 do zgrubnej i T5 D2 do wykańczającej. Zużycie wpisujesz dla konkretnego D. D0 wyłącza korekcję.'],
  ['nominal','Nominał','Wymiar z rysunku bez tolerancji, np. Ø20 albo 15 mm.'],
  ['odchylki','Odchyłki (tolerancja)','O ile wymiar może się różnić od nominału. Ø20 +0.021/0 → dobry od 20.000 do 20.021. 15 ±0.05 → górna +0.05, dolna −0.05. Pasowanie Ø20 H7 to +0.021/0, Ø20 g6 to −0.007/−0.020. Puste pole = 0.'],
  ['srodek-tol','Środek tolerancji','Środek między wymiarem min i max. Celując w środek, masz najwięcej zapasu na zużycie narzędzia i rozrzut maszyny. „Nominał” celuje w wymiar z rysunku, „Własny” w dowolną wartość.'],
  ['srodek-wym','Środek wymiaru (w programie)','Współrzędna środka kształtu w programie. Kieszeń od X−20 do X20 ma środek X0. Czop od X10 do X50 ma środek X30. Punkty po obu stronach środka rozsuną się o połowę zmiany.'],
  ['srednica','Korekcja promienia w średnicy','Niektóre Fanuc mają parametr, przy którym korekcję promienia wpisuje się jako średnicę. Jeśli nie wiesz — zostaw wyłączone. Sprawdzisz po geometrii: frez Ø10 z wpisem 5 = promień, z wpisem 10 = średnica.'],
  ['obecne','Obecne zużycie','Wartość, która teraz stoi w kolumnie zużycia dla tego narzędzia. Jeśli ją wpiszesz, aplikacja poda od razu całą nową wartość. Bez niej dostaniesz tylko poprawkę do dodania.'],
  ['input-plus','[+WPROWADŹ] / [+INPUT]','Na Fanuc dodaje wpisaną liczbę do wartości w komórce. [WPROWADŹ] / [INPUT] zastępuje wartość. Do korekt z pomiaru bezpieczniej używać [+WPROWADŹ].'],
  ['pamiec-abc','Pamięć korekcji A / B / C (Fanuc)','A — jedna kolumna na numer (geometria i zużycie razem). B — osobno geometria i zużycie. C — osobno długość (H) i promień (D), każda z geometrią i zużyciem. Najczęściej spotkasz C.'],
  ['punkt-zerowy','Punkt zerowy detalu (G54…)','Miejsce na detalu, od którego liczone są wymiary w programie. Ustawiasz je sondą lub ręcznie i zapisujesz w tabeli przesunięć (G54, G55…).'],
  ['modalny','Kod modalny','Działa do odwołania. G01 albo F800 zostają aktywne w kolejnych liniach, aż wpiszesz inny kod z tej samej grupy. Kod niemodalny (np. G04, G53) działa tylko w swojej linii.'],
  ['abs-inc','Absolutnie / przyrostowo','G90: X50 = jedź do punktu 50 od zera detalu. G91: X50 = przesuń się o 50 mm od miejsca, w którym jesteś.'],
  ['plaszczyzna','Płaszczyzna G17 / G18 / G19','Określa, w której płaszczyźnie liczone są łuki, korekcja promienia i cykle. Frezarka pionowa: prawie zawsze G17 (XY), narzędzie wzdłuż Z.'],
  ['cykl','Cykl','Gotowy ruch zapisany w sterowaniu, np. wiercenie z wycofaniem. Podajesz tylko pozycję i parametry (głębokość, wysokość R, krok Q), a sterowanie robi resztę.'],
  ['plaszczyzna-r','Płaszczyzna R (bezpieczna)','Wysokość nad detalem, do której cykl dojeżdża szybko, zanim zacznie wiercić z posuwem. Zwykle 1–3 mm nad powierzchnią.'],
  ['tcp','TCP — kontrola czubka narzędzia','TCP (Tool Center Point) to „pilnowanie czubka narzędzia”. Przy obróbce 5 osiami naraz stół się obraca i pochyla, więc czubek narzędzia zmieniałby położenie względem detalu. Z włączonym TCP sterowanie samo dolicza ruchy X, Y, Z, żeby czubek szedł dokładnie po torze z programu. Fanuc: G43.4 (wyłączasz G49). Sinumerik: TRAORI (wyłączasz TRAFOOF). Spotkasz to w programach 5-osiowych z CAM, np. na Matsuurze MX-330.'],
  ['pochylona','Płaszczyzna pochylona (3+2)','Obróbka pochylonej ściany tak, jakby była płaska. Stół obraca się o kąt i stoi, a układ współrzędnych obraca się razem z nim. Potem robisz zwykłe frezowanie i wiercenie w X/Y/Z tej płaszczyzny. Różnica od TCP: tu osie obrotowe stoją podczas skrawania. Fanuc: G68.2 + G53.1, koniec G69. Sinumerik: CYCLE800.'],
  ['krancowka','Krańcówka programowa','Granica ruchu osi zapisana w sterowaniu, przed fizyczną krańcówką. Alarm pojawia się, gdy program lub korekcja kazałyby osi wyjechać dalej.'],
  ['sucho','Przejazd na sucho','Uruchomienie programu bez skrawania: nad detalem, ze zmniejszonym posuwem lub w trybie testu. Sprawdzasz tor przed pierwszą sztuką.'],
  ['wspolbiezne','Frezowanie współbieżne / przeciwbieżne','Współbieżne: ząb wchodzi w gruby wiór i wychodzi na cienkim — lepsza powierzchnia, standard na CNC. Przy M3 to G41: kontur zewnętrzny zgodnie z zegarem, kieszeń przeciwnie.']
];

/* Pełne listy kodów (zakładka Wiedza → Kody → Pełna lista).
   [kod, opis, grupa (R ruch, U układy, K korekcje, C cykle, P program, 5 osi, M), 1 = opcja sterowania]
   Fanuc: seria 30i/31i/32i-B, wersja frezarska (M). Sinumerik: 840D sl. Z wiedzy ogólnej — dostępność zależy od opcji i producenta maszyny. */
var FULL_CODES = {
  fanuc: [
    ['G00','Ruch szybki (pozycjonowanie)','R'],
    ['G01','Interpolacja liniowa — skrawanie po prostej z posuwem F','R'],
    ['G02','Łuk / helisa zgodnie z ruchem zegara','R'],
    ['G03','Łuk / helisa przeciwnie do ruchu zegara','R'],
    ['G02.2 / G03.2','Interpolacja ewolwentowa','R',1],
    ['G02.3 / G03.3','Interpolacja wykładnicza','R',1],
    ['G02.4 / G03.4','Łuk przestrzenny 3D przez punkt pośredni','R',1],
    ['G04','Postój (P w ms albo X w s)','R'],
    ['G05','Obróbka szybka / AI kontur (np. G05 P10000)','R',1],
    ['G05.1','AI kontur (Q1), interpolacja gładka (Q2), Nano smoothing (Q3); Q0 wyłącza','R',1],
    ['G05.4','Sterowanie HRV3 wł./wył.','R',1],
    ['G06.2','Interpolacja NURBS','R',1],
    ['G07','Interpolacja z osią wirtualną','R',1],
    ['G07.1 (G107)','Interpolacja cylindryczna (frezowanie na walcu)','R',1],
    ['G08','Kontrola wyprzedzająca AI (G08 P1 wł., P0 wył.)','R',1],
    ['G09','Dokładne zatrzymanie (tylko w tym bloku)','R'],
    ['G10','Wpis danych z programu: korekcje (L10–L13), punkty zerowe (L2, L20), parametry (L50)','P'],
    ['G10.6','Wycofanie i powrót narzędzia','R',1],
    ['G11','Koniec wpisu danych z programu (po G10 L50)','P'],
    ['G12.1','Interpolacja we współrzędnych biegunowych — włącz','R',1],
    ['G13.1','Interpolacja we współrzędnych biegunowych — wyłącz','R',1],
    ['G15','Programowanie biegunowe (promień, kąt) — wyłącz','U',1],
    ['G16','Programowanie biegunowe (promień, kąt) — włącz','U',1],
    ['G17','Płaszczyzna XY','U'],
    ['G18','Płaszczyzna ZX','U'],
    ['G19','Płaszczyzna YZ','U'],
    ['G20','Programowanie w calach','U'],
    ['G21','Programowanie w milimetrach','U'],
    ['G22','Kontrola strefy zabronionej (krańcówka programowa 2/3) — włącz','U'],
    ['G23','Kontrola strefy zabronionej — wyłącz','U'],
    ['G25','Kontrola wahań obrotów wrzeciona — wyłącz','R',1],
    ['G26','Kontrola wahań obrotów wrzeciona — włącz','R',1],
    ['G27','Sprawdzenie powrotu do punktu referencyjnego','U'],
    ['G28','Zjazd do punktu referencyjnego (zwykle G91 G28 Z0.)','U'],
    ['G29','Ruch z punktu referencyjnego','U'],
    ['G30','Zjazd do 2./3./4. punktu referencyjnego (P2–P4), np. pozycja zmiany narzędzia','U'],
    ['G30.1','Zjazd do pływającego punktu referencyjnego','U',1],
    ['G31','Ruch z przerwaniem sygnałem (pomiar sondą, skip)','R'],
    ['G33','Gwintowanie nożem (stały skok)','R',1],
    ['G37','Automatyczny pomiar długości narzędzia','K',1],
    ['G38','Korekcja promienia — zachowaj wektor w tym bloku','K'],
    ['G39','Korekcja promienia — łuk w narożniku','K'],
    ['G40','Wyłączenie korekcji promienia','K'],
    ['G41','Korekcja promienia — frez po lewej stronie konturu','K'],
    ['G42','Korekcja promienia — frez po prawej stronie konturu','K'],
    ['G40.1 / G41.1 / G42.1','Sterowanie kierunkiem normalnym (wył. / lewo / prawo)','K',1],
    ['G41.2 / G42.2','Korekcja promienia 3D (5 osi, strona narzędzia)','5',1],
    ['G41.3','Korekcja promienia 3D (krawędź natarcia)','5',1],
    ['G43','Korekcja długości narzędzia +','K'],
    ['G44','Korekcja długości narzędzia −','K'],
    ['G43.1','Korekcja długości wzdłuż osi narzędzia','5',1],
    ['G43.4','TCP — kontrola czubka narzędzia, typ 1','5',1],
    ['G43.5','TCP — kontrola czubka narzędzia, typ 2 (wektor I J K)','5',1],
    ['G45 – G48','Stara korekcja narzędzia: zwiększ / zmniejsz / 2× (rzadko używane)','K'],
    ['G49','Wyłączenie korekcji długości (także G43.4/G43.5)','K'],
    ['G50','Skalowanie — wyłącz','U',1],
    ['G51','Skalowanie — włącz','U',1],
    ['G50.1','Lustro programowe — wyłącz','U'],
    ['G51.1','Lustro programowe — włącz','U'],
    ['G52','Lokalny układ współrzędnych (przesunięcie tymczasowe)','U'],
    ['G53','Ruch w układzie maszyny (tylko w tym bloku)','U'],
    ['G53.1','Ustawienie osi obrotowych po G68.2 (kierunek narzędzia)','5',1],
    ['G54 – G59','Układy współrzędnych detalu 1–6','U'],
    ['G54.1 P1–P48','Dodatkowe układy współrzędnych (do P300 z opcją)','U',1],
    ['G54.2','Dynamiczne przesunięcie dla stołu obrotowego','5',1],
    ['G54.4','Kompensacja błędu ustawienia detalu','5',1],
    ['G60','Pozycjonowanie jednokierunkowe','R',1],
    ['G61','Tryb dokładnego zatrzymania','R'],
    ['G62','Automatyczne zmniejszanie posuwu w narożach','R'],
    ['G63','Tryb gwintowania (bez korekty posuwu)','R'],
    ['G64','Tryb skrawania ciągłego (standard)','R'],
    ['G65','Wywołanie makra (jednorazowe)','P'],
    ['G66','Wywołanie makra modalne','P'],
    ['G66.1','Wywołanie makra modalne w każdym bloku','P',1],
    ['G67','Koniec wywołania modalnego makra','P'],
    ['G68','Obrót układu współrzędnych','U',1],
    ['G68.2','Płaszczyzna pochylona (3+2)','5',1],
    ['G68.3','Płaszczyzna pochylona z kierunku narzędzia','5',1],
    ['G68.4','Płaszczyzna pochylona — przyrostowo','5',1],
    ['G69','Koniec obrotu / płaszczyzny pochylonej','U'],
    ['G72.1','Kopiowanie konturu z obrotem','P',1],
    ['G72.2','Kopiowanie konturu z przesunięciem','P',1],
    ['G73','Cykl wiercenia z łamaniem wióra','C'],
    ['G74','Cykl gwintowania lewego','C'],
    ['G76','Cykl wytaczania dokładnego (z orientacją i odsunięciem noża)','C'],
    ['G80','Koniec cyklu wiercenia','C'],
    ['G81','Cykl wiercenia / nawiercania','C'],
    ['G82','Cykl wiercenia z postojem (pogłębianie)','C'],
    ['G83','Cykl wiercenia głębokiego z wycofaniem','C'],
    ['G84','Cykl gwintowania prawego (sztywne z M29)','C'],
    ['G85','Cykl rozwiercania / wytaczania (wyjazd z posuwem)','C'],
    ['G86','Cykl wytaczania (stop wrzeciona na dnie, wyjazd szybki)','C'],
    ['G87','Cykl wytaczania wstecznego','C'],
    ['G88','Cykl wytaczania z postojem i ręcznym wyjazdem','C'],
    ['G89','Cykl wytaczania z postojem, wyjazd z posuwem','C'],
    ['G90','Programowanie absolutne','U'],
    ['G91','Programowanie przyrostowe','U'],
    ['G91.1','Kontrola maksymalnego ruchu przyrostowego','U',1],
    ['G92','Ustawienie układu współrzędnych / ograniczenie obrotów','U'],
    ['G92.1','Reset układu współrzędnych detalu (preset)','U'],
    ['G93','Posuw w odwrotności czasu','R',1],
    ['G94','Posuw w mm/min','R'],
    ['G95','Posuw w mm/obr','R'],
    ['G96','Stała prędkość skrawania','R',1],
    ['G97','Stałe obroty (koniec G96)','R'],
    ['G98','Powrót w cyklu do poziomu startowego','C'],
    ['G99','Powrót w cyklu do płaszczyzny R','C'],
    ['M00','Stop programu (zawsze)','M'],
    ['M01','Stop opcjonalny (gdy włączony przycisk)','M'],
    ['M02','Koniec programu','M'],
    ['M03','Wrzeciono w prawo','M'],
    ['M04','Wrzeciono w lewo','M'],
    ['M05','Stop wrzeciona','M'],
    ['M06','Zmiana narzędzia','M'],
    ['M07','Chłodzenie mgłą / powietrzem (zwykle — zależy od maszyny)','M'],
    ['M08','Chłodziwo włączone','M'],
    ['M09','Chłodziwo wyłączone','M'],
    ['M19','Orientacja wrzeciona','M'],
    ['M29','Gwintowanie sztywne (przed G84) — numer ustawiany parametrem','M'],
    ['M30','Koniec programu z powrotem na początek','M'],
    ['M98','Wywołanie podprogramu','M'],
    ['M99','Koniec podprogramu / powrót','M'],
    ['M198','Wywołanie podprogramu z pamięci zewnętrznej (karta, serwer)','M',1]
  ],
  sinumerik: [
    ['G0','Ruch szybki','R'],
    ['G1','Interpolacja liniowa z posuwem F','R'],
    ['G2','Łuk zgodnie z ruchem zegara (CR=, I/J/K albo AR=)','R'],
    ['G3','Łuk przeciwnie do ruchu zegara','R'],
    ['CIP','Łuk przez punkt pośredni (I1=, J1=, K1=)','R'],
    ['CT','Łuk styczny do poprzedniego ruchu','R'],
    ['G33','Gwintowanie nożem (stały skok)','R'],
    ['G331 / G332','Gwintowanie sztywne: wejście / wyjście','R'],
    ['G63','Gwintowanie z oprawką kompensacyjną','R'],
    ['G4','Postój (F w s albo S w obrotach)','R'],
    ['G9','Dokładne zatrzymanie (tylko w tym bloku)','R'],
    ['G60','Tryb dokładnego zatrzymania','R'],
    ['G601 / G602 / G603','Okno dokładnego zatrzymania: dokładne / zgrubne / koniec interpolacji','R'],
    ['G64','Praca ciągła (bez zatrzymań na styku bloków)','R'],
    ['G641 / G642 / G643 / G644 / G645','Praca ciągła z zaokrąglaniem przejść (ADIS=, tolerancje)','R'],
    ['SOFT / BRISK','Przyspieszenie z ograniczeniem szarpnięcia / skokowe','R'],
    ['FFWON / FFWOF','Sterowanie wyprzedzające włącz / wyłącz','R'],
    ['CYCLE832','Obróbka szybka HSC — tolerancja i tryb (zgrubna, wykańczająca)','R'],
    ['COMPON / COMPCURV / COMPCAD / COMPOF','Kompresor bloków z CAM włącz / wyłącz','R',1],
    ['G17 / G18 / G19','Płaszczyzna XY / ZX / YZ','U'],
    ['G70 / G71','Cale / milimetry (tylko geometria)','U'],
    ['G700 / G710','Cale / milimetry (geometria i posuw)','U'],
    ['G90 / G91','Programowanie absolutne / przyrostowe','U'],
    ['AC / IC','Absolutnie / przyrostowo dla jednej wartości, np. X=IC(5)','U'],
    ['G93 / G94 / G95','Posuw w odwrotności czasu / mm/min / mm/obr','R'],
    ['G96 / G97','Stała prędkość skrawania / stałe obroty','R'],
    ['LIMS','Ograniczenie obrotów przy G96','R'],
    ['G25 / G26','Dolne / górne ograniczenie obrotów wrzeciona albo strefy pracy','U'],
    ['WALIMON / WALIMOF','Ograniczenie strefy pracy włącz / wyłącz','U'],
    ['G40','Wyłączenie korekcji promienia','K'],
    ['G41 / G42','Korekcja promienia — frez po lewej / prawej','K'],
    ['G450 / G451','Przejście w narożniku przy korekcji: łuk / przecięcie','K'],
    ['NORM / KONT / KONTC / KONTT','Sposób dojazdu i odjazdu przy korekcji promienia','K'],
    ['G147 / G148','Miękki dojazd / odjazd po prostej (SAR)','K'],
    ['G247 / G248','Miękki dojazd / odjazd po ćwiartce koła','K'],
    ['G347 / G348','Miękki dojazd / odjazd po półokręgu','K'],
    ['DISR / DISCL','Odległość dojazdu / bezpieczna wysokość dla SAR','K'],
    ['T / D','Wybór narzędzia / ostrza (włącza korekcję długości i promienia)','K'],
    ['D0','Wyłączenie korekcji narzędzia','K'],
    ['G53','Ruch bez przesunięć ustawialnych (w tym bloku)','U'],
    ['G153','Ruch bez przesunięć i bez ramki bazowej','U'],
    ['SUPA','Ruch w układzie maszyny, bez wszystkich przesunięć','U'],
    ['G500','Wyłączenie przesunięcia ustawialnego (G54…)','U'],
    ['G54 – G57','Przesunięcia punktu zerowego 1–4','U'],
    ['G505 – G599','Kolejne przesunięcia punktu zerowego','U'],
    ['G74','Najazd na punkt referencyjny z programu','U'],
    ['G75','Najazd na punkt stały (np. zmiany narzędzia)','U'],
    ['TRANS / ATRANS','Przesunięcie programowe: absolutne / dodawane','U'],
    ['ROT / AROT','Obrót układu: absolutny / dodawany','U'],
    ['ROTS / AROTS','Obrót układu podany kątami przestrzennymi','U'],
    ['SCALE / ASCALE','Skalowanie programowe','U'],
    ['MIRROR / AMIRROR','Lustro programowe','U'],
    ['TOFRAME / TOROT','Ustawienie układu wzdłuż osi narzędzia','5',1],
    ['CYCLE800','Płaszczyzna pochylona (3+2) i obrót osi','5',1],
    ['TRAORI / TRAFOOF','Transformacja 5-osiowa z TCP włącz / wyłącz','5',1],
    ['TRANSMIT','Frezowanie czołowe na tokarce / osi obrotowej','5',1],
    ['TRACYL','Frezowanie na powierzchni walca','5',1],
    ['G110 / G111 / G112','Biegun dla współrzędnych biegunowych (względnie / absolutnie / od poprzedniego)','U'],
    ['AP / RP','Kąt / promień biegunowy','U'],
    ['CHF / CHR','Fazka (długość fazki / długość boku)','R'],
    ['RND / RNDM','Zaokrąglenie narożnika (jednorazowe / modalne)','R'],
    ['FRC / FRCM','Posuw dla fazki / zaokrąglenia','R'],
    ['SPOS','Pozycjonowanie (orientacja) wrzeciona','R'],
    ['STOPRE','Stop przetwarzania z wyprzedzeniem (np. przed odczytem zmiennych)','P'],
    ['MSG','Komunikat dla operatora na ekranie','P'],
    ['DEF','Definicja zmiennej użytkownika','P'],
    ['R0 – R99','Parametry obliczeniowe (R-parametry)','P'],
    ['GOTOF / GOTOB / GOTO / GOTOC','Skok do etykiety do przodu / wstecz / w obie strony','P'],
    ['IF … ELSE … ENDIF','Warunek','P'],
    ['WHILE / FOR / LOOP / REPEAT','Pętle programowe','P'],
    ['CASE','Skok zależny od wartości','P'],
    ['CALL / PCALL','Wywołanie podprogramu','P'],
    ['MCALL','Modalne wywołanie podprogramu lub cyklu (samo MCALL wyłącza)','P'],
    ['EXTCALL','Wywołanie programu z pamięci zewnętrznej','P'],
    ['RET / M17','Koniec podprogramu','P'],
    ['CYCLE81','Wiercenie / nawiercanie','C'],
    ['CYCLE82','Wiercenie z postojem (pogłębianie)','C'],
    ['CYCLE83','Wiercenie głębokie (z wycofaniem albo łamaniem wióra)','C'],
    ['CYCLE84','Gwintowanie sztywne','C'],
    ['CYCLE840','Gwintowanie z oprawką kompensacyjną','C'],
    ['CYCLE85','Rozwiercanie (wyjazd z posuwem)','C'],
    ['CYCLE86','Wytaczanie (orientacja wrzeciona i odsunięcie)','C'],
    ['CYCLE87 / CYCLE88','Wytaczanie z zatrzymaniem','C'],
    ['CYCLE89','Wytaczanie z postojem','C'],
    ['HOLES1 / HOLES2','Otwory w rzędzie / na okręgu','C'],
    ['CYCLE801','Otwory w siatce / ramce','C'],
    ['CYCLE802','Dowolne pozycje otworów','C'],
    ['POCKET3 / POCKET4','Kieszeń prostokątna / okrągła','C'],
    ['CYCLE76 / CYCLE77','Czop prostokątny / okrągły','C'],
    ['SLOT1 / SLOT2 / LONGHOLE','Rowki na okręgu / okrągłe / otwory podłużne','C'],
    ['CYCLE899','Rowek otwarty','C'],
    ['CYCLE61','Frezowanie płaszczyzny','C'],
    ['CYCLE62 / CYCLE63 / CYCLE64','Kontur: wywołanie / frezowanie kieszeni / wiercenie wstępne','C'],
    ['CYCLE72','Frezowanie po konturze','C'],
    ['CYCLE70','Frezowanie gwintu','C'],
    ['CYCLE60','Grawerowanie','C'],
    ['CYCLE971 / CYCLE982','Pomiar narzędzia (sonda narzędziowa)','C',1],
    ['CYCLE976 / CYCLE977 / CYCLE978 / CYCLE979','Pomiar detalu sondą (kalibracja, otwór/czop, płaszczyzna, na okręgu)','C',1],
    ['M0 / M1','Stop programu / stop opcjonalny','M'],
    ['M2 / M30','Koniec programu','M'],
    ['M3 / M4 / M5','Wrzeciono w prawo / w lewo / stop','M'],
    ['M6','Zmiana narzędzia','M'],
    ['M7 / M8 / M9','Chłodzenie mgłą / chłodziwo wł. / wył. (zależy od maszyny)','M'],
    ['M17','Koniec podprogramu','M'],
    ['M19','Orientacja wrzeciona (zależy od ustawień maszyny; zwykle SPOS)','M'],
    ['M40 – M45','Wybór biegu wrzeciona (automatyczny, 1–5)','M'],
    ['M70','Przełączenie wrzeciona w tryb osi','M',1]
  ]
};
/* Kody M producenta maszyny (znane z opisów alarmów maszyny — pełna lista jest w instrukcji maszyny) */
var MACHINE_M = {
  chiron: [
    ['M187','Sonda stołowa włączona (z opisu alarmu 700106)','M'],
    ['M88','Funkcja serwisowa (alarm 700161 „M88 aktywna”)','M'],
    ['M90','Funkcja serwisowa zmieniacza narzędzi (alarm 700160)','M'],
    ['M555','Tryb ustawiania zmieniacza narzędzi (alarm 700733)','M']
  ]
};
